/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handler

import (
	"github.com/gin-gonic/gin"
)

type VehicleManagementAPI interface {

	// VehiclesGet Get /api/vehicles
	// List ambulance vehicles
	VehiclesGet(c *gin.Context)

	// VehiclesPost Post /api/vehicles
	// Register a new ambulance vehicle
	VehiclesPost(c *gin.Context)

	// VehiclesVehicleIdDelete Delete /api/vehicles/:vehicleId
	// Remove ambulance vehicle from registry
	VehiclesVehicleIdDelete(c *gin.Context)

	// VehiclesVehicleIdGet Get /api/vehicles/:vehicleId
	// Get ambulance vehicle detail
	VehiclesVehicleIdGet(c *gin.Context)

	// VehiclesVehicleIdPut Put /api/vehicles/:vehicleId
	// Update ambulance vehicle
	VehiclesVehicleIdPut(c *gin.Context)

	// VehiclesVehicleIdStatusPatch Patch /api/vehicles/:vehicleId/status
	// Update ambulance vehicle status
	VehiclesVehicleIdStatusPatch(c *gin.Context)
}
