/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handler

import (
	"github.com/gin-gonic/gin"
)

type DispatchManagementAPI interface {

	// DispatchesDispatchIdDelete Delete /api/dispatches/:dispatchId
	// Cancel ambulance dispatch
	DispatchesDispatchIdDelete(c *gin.Context)

	// DispatchesDispatchIdGet Get /api/dispatches/:dispatchId
	// Get ambulance dispatch detail
	DispatchesDispatchIdGet(c *gin.Context)

	// DispatchesDispatchIdPut Put /api/dispatches/:dispatchId
	// Update ambulance dispatch
	DispatchesDispatchIdPut(c *gin.Context)

	// DispatchesDispatchIdStatusPatch Patch /api/dispatches/:dispatchId/status
	// Update ambulance dispatch status
	DispatchesDispatchIdStatusPatch(c *gin.Context)

	// DispatchesGet Get /api/dispatches
	// List ambulance dispatches
	DispatchesGet(c *gin.Context)

	// DispatchesPost Post /api/dispatches
	// Create ambulance dispatch
	DispatchesPost(c *gin.Context)
}
