/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// VehicleStatus : Supported vehicle lifecycle and availability states.
type VehicleStatus string

// List of VehicleStatus
const (
	AVAILABLE      VehicleStatus = "AVAILABLE"
	ON_MISSION     VehicleStatus = "ON_MISSION"
	OUT_OF_SERVICE VehicleStatus = "OUT_OF_SERVICE"
	IN_SERVICE     VehicleStatus = "IN_SERVICE"
)
