/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type VehicleUpdateRequest struct {
	CallSign string `json:"callSign"`

	VehicleType string `json:"vehicleType"`

	PlateNumber string `json:"plateNumber"`

	Station string `json:"station"`

	AssignedCrew string `json:"assignedCrew,omitempty"`

	Status VehicleStatus `json:"status"`

	MileageKm int32 `json:"mileageKm"`

	LastServiceDate string `json:"lastServiceDate"`

	Notes string `json:"notes,omitempty"`
}
