/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"time"
)

type DispatchCreateRequest struct {
	IncidentNumber string `json:"incidentNumber"`

	CallerName string `json:"callerName"`

	PatientName string `json:"patientName"`

	StreetAddress string `json:"streetAddress"`

	City string `json:"city"`

	DispatchReason string `json:"dispatchReason"`

	Priority DispatchPriority `json:"priority"`

	Status DispatchStatus `json:"status"`

	AmbulanceCallSign string `json:"ambulanceCallSign"`

	DestinationHospital string `json:"destinationHospital"`

	DispatcherName string `json:"dispatcherName"`

	CreatedAt time.Time `json:"createdAt"`

	Notes string `json:"notes,omitempty"`
}
