/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// DispatchStatus : Supported ambulance dispatch workflow states.
type DispatchStatus string

// List of DispatchStatus
const (
	ACCEPTED                 DispatchStatus = "ACCEPTED"
	EN_ROUTE                 DispatchStatus = "EN_ROUTE"
	ON_SCENE                 DispatchStatus = "ON_SCENE"
	TRANSPORTING_TO_HOSPITAL DispatchStatus = "TRANSPORTING_TO_HOSPITAL"
	COMPLETED                DispatchStatus = "COMPLETED"
)
