/*
 * Ambulance Management API
 *
 * API contract for ambulance management modules including fleet and dispatch management.
 *
 * API version: 1.0.0
 * Contact: xfedunchyk@stuba.sk, xskrypova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// DispatchPriority : Triage priority assigned to the dispatch.
type DispatchPriority string

// List of DispatchPriority
const (
	LOW      DispatchPriority = "LOW"
	MEDIUM   DispatchPriority = "MEDIUM"
	HIGH     DispatchPriority = "HIGH"
	CRITICAL DispatchPriority = "CRITICAL"
)
