services:
  mongo:
    image: mongo:8.2.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AMBULANCE_MANAGEMENT_API_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${AMBULANCE_MANAGEMENT_API_MONGODB_PASSWORD}
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${AMBULANCE_MANAGEMENT_API_MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${AMBULANCE_MANAGEMENT_API_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress
    depends_on:
      - mongo
volumes:
  db_data: {}